export { default as Back } from "./arrow_left.png";
export { default as Close } from "./ph_x.png";
export { default as Menu } from "./hambg-menu.png";
export { default as Login } from "./login.png";
export { default as CheckBL } from "./check_black.png";
export { default as Search } from "./search.png";
export { default as Upload } from "./upload.png";
export { default as Ok } from "./ok.png";
export { default as No } from "./no.png";
